### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by muneebarif11** [Crescent-Labs/iqra-api#1]
How to make api calls with speech? i mean in description it mentioned that Quran surah will be fetched based on speech. Kindly show any example or help me out.

Thanks

**Comment by mmmoussa** [comment]
The speech-to-text is done on the client-side, not as part of the api in this repo. The text result of speech-to-text is then sent to this api. Take a look at the [website](https://github.com/Crescent-Labs/iqra-web), [Android client](https://github.com/Crescent-Labs/iqra-android), and [iOS client](https://github.com/Crescent-Labs/iqra-ios) repos to see how to implement the speech-to-text on different platforms.
